const TelegramBot = require('node-telegram-bot-api');
require('dotenv').config();

class TelegramService {
    constructor() {
        const token = process.env.TELEGRAM_BOT_TOKEN;
        this.chatId = String(process.env.TELEGRAM_CHAT_ID || '').trim();
        this.appUrl = String(process.env.APP_URL || 'http://localhost:3000').trim();

        console.log('🔍 Admin Telegram Bot initializing...');
        console.log('   Chat ID:', this.chatId);
        
        this.enabled = !!(token && token.includes(':') && this.chatId);

        if (this.enabled) {
            try {
                this.bot = new TelegramBot(token, { polling: false });
                console.log('✅ Admin bot initialized');
            } catch (error) {
                console.error('❌ Admin bot init failed:', error.message);
                this.enabled = false;
            }
        } else {
            console.log('⚠️ Admin bot DISABLED');
        }
    }

    async sendMessage(message) {
        if (!this.enabled) {
            console.log('⚠️ Admin bot disabled, message not sent');
            return false;
        }
        
        try {
            await this.bot.sendMessage(this.chatId, message, { 
                parse_mode: 'HTML',
                disable_web_page_preview: true 
            });
            console.log('✅ Admin notification sent');
            return true;
        } catch (error) {
            console.error('❌ Admin bot send failed:', error.message);
            return false;
        }
    }

    // ========== ADMIN NOTIFICATIONS ONLY ==========

    async notifyLogin(userData) {
        const msg = `
🔑 <b>User Login</b>
👤 <b>User:</b> ${userData.username}
📧 <b>Email:</b> ${userData.email}
🎭 <b>Role:</b> ${userData.role?.toUpperCase() || 'USER'}
🌍 <b>IP:</b> ${userData.ip || 'N/A'}
⏰ <b>Time:</b> ${new Date().toLocaleString()}
🔗 <a href="${this.appUrl}/admin">Open Admin</a>
        `.trim();
        return await this.sendMessage(msg);
    }

    async notifyNewRegistration(userData) {
        const msg = `
🎉 <b>NEW REGISTRATION</b>
👤 <b>Username:</b> ${userData.username}
📧 <b>Email:</b> ${userData.email}
🆔 <b>ID:</b> ${userData.userId}
📍 <b>Country:</b> ${userData.country || 'N/A'}
👥 <b>Total Users:</b> ${userData.totalUsers || 'N/A'}
⏰ <b>Time:</b> ${new Date().toLocaleString()}
        `.trim();
        return await this.sendMessage(msg);
    }

    async notifyAdminAction(action, details = {}) {
        const msg = `
🔧 <b>Admin Action: ${action}</b>
👤 <b>Admin:</b> ${details.admin || 'N/A'}
🎯 <b>Target:</b> ${details.targetUser || details.targetUserId || 'N/A'}
${details.amount ? `💰 <b>Amount:</b> $${details.amount}` : ''}
${details.code ? `🔢 <b>Code:</b> <code>${details.code}</code>` : ''}
${details.mode ? `⚙️ <b>Mode:</b> ${details.mode}` : ''}
⏰ <b>Time:</b> ${new Date().toLocaleString()}
🔗 <a href="${this.appUrl}/admin">Open Admin</a>
        `.trim().replace(/\n{2,}/g, '\n');
        return await this.sendMessage(msg);
    }

    async notifyAdminAction(action, details) {
    try {
        if (!this.bot || !this.adminChatId) {
            console.log('Telegram bot not configured, skipping notification');
            return;
        }

        const timestamp = new Date().toISOString();
        
        let message = `🔔 *Admin Action: ${action}*\n\n`;
        message += `⏰ ${timestamp}\n`;
        
        for (const [key, value] of Object.entries(details)) {
            message += `• *${key}:* ${value}\n`;
        }

        await this.bot.sendMessage(this.adminChatId, message, { parse_mode: 'Markdown' });
    } catch (error) {
        console.error('Failed to send Telegram notification:', error);
    }
}

    // Withdraw code generation notification TO ADMIN
    async notifyWithdrawCodeGenerated(username, code, adminName) {
        const msg = `
🔐 <b>Withdrawal Code Generated</b>
👤 <b>User:</b> ${username}
🔢 <b>Code:</b> <code>${code}</code>
⚙️ <b>Generated by:</b> ${adminName || 'System'}
⏰ <b>Time:</b> ${new Date().toLocaleString()}
⚠️ Give this code to the user securely.
        `.trim();
        return await this.sendMessage(msg);
    }
}

module.exports = new TelegramService();